# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"\"\n\x11SquareRootRequest\x12\r\n\x05value\x18\x01 \x01(\x01\"#\n\x12SquareRootResponse\x12\r\n\x05value\x18\x01 \x01(\x01\x32[\n\nCalculator\x12M\n\nSquareRoot\x12\x1d.calculator.SquareRootRequest\x1a\x1e.calculator.SquareRootResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SQUAREROOTREQUEST']._serialized_start=32
  _globals['_SQUAREROOTREQUEST']._serialized_end=66
  _globals['_SQUAREROOTRESPONSE']._serialized_start=68
  _globals['_SQUAREROOTRESPONSE']._serialized_end=103
  _globals['_CALCULATOR']._serialized_start=105
  _globals['_CALCULATOR']._serialized_end=196
# @@protoc_insertion_point(module_scope)
